// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeORHn1UOdlb-A8d6GZ5Z7xrmTaAR1OyY',
    appId: '1:827134159233:web:1d1e9b32e7e1d742976080',
    messagingSenderId: '827134159233',
    projectId: 'tutorial-flutter-1',
    authDomain: 'tutorial-flutter-1.firebaseapp.com',
    storageBucket: 'tutorial-flutter-1.appspot.com',
    measurementId: 'G-6MH6PMY7TX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT_HqNXTOjHlxiumMgTS8vVa4ffXxTKQw',
    appId: '1:827134159233:android:2c5bbdf549c0fc5c976080',
    messagingSenderId: '827134159233',
    projectId: 'tutorial-flutter-1',
    storageBucket: 'tutorial-flutter-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjcKU3N_NeJO90TWdZVgGj24hAJHfSXvk',
    appId: '1:827134159233:ios:1cf87fce5a00f556976080',
    messagingSenderId: '827134159233',
    projectId: 'tutorial-flutter-1',
    storageBucket: 'tutorial-flutter-1.appspot.com',
    iosBundleId: 'dev.triyono.projekTutorial1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjcKU3N_NeJO90TWdZVgGj24hAJHfSXvk',
    appId: '1:827134159233:ios:412d61dbb50e1107976080',
    messagingSenderId: '827134159233',
    projectId: 'tutorial-flutter-1',
    storageBucket: 'tutorial-flutter-1.appspot.com',
    iosBundleId: 'dev.triyono.projekTutorial1.RunnerTests',
  );
}
